exclude = [
  "migrations"
]

line-length = 99
indent-width = 4

target-version = "py311"

[lint]
select = [
  "W",
  "E",
  "F",
  "UP",
  "N",
  "I",
  "YTT",
  "S"
]

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "double"

indent-style = "space"

skip-magic-trailing-comma = false

line-ending = "auto"

docstring-code-format = false

[lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]

[lint.pydocstyle]
convention = "numpy"