"""New_database

Revision ID: 22d7eac0a6cd
Revises: efd536a0f441
Create Date: 2024-04-13 14:44:45.178557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d7eac0a6cd'
down_revision: Union[str, None] = 'efd536a0f441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_agency_summaries', 'rating_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_agency_summaries', sa.Column('rating_details', sa.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
